# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import holdings_pb2 as holdings__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in holdings_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KiteServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHoldings = channel.unary_unary(
                '/holdings.KiteService/GetHoldings',
                request_serializer=holdings__pb2.HoldingsRequest.SerializeToString,
                response_deserializer=holdings__pb2.HoldingsResponse.FromString,
                _registered_method=True)


class KiteServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetHoldings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KiteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHoldings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHoldings,
                    request_deserializer=holdings__pb2.HoldingsRequest.FromString,
                    response_serializer=holdings__pb2.HoldingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'holdings.KiteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('holdings.KiteService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KiteService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHoldings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/holdings.KiteService/GetHoldings',
            holdings__pb2.HoldingsRequest.SerializeToString,
            holdings__pb2.HoldingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
